[[headers]]
  for = "/lib/book/antologia-mujer-2025.pdf"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/lib/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/lib/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"